### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by jochenchrist** [datacontract/datacontract-specification#10]
Do we need a (better) way to express semantics within a data contract?

We want to embrace business experts in collaborating with data contracts.

The current schema representation might not be sufficient:
- Not all schemas have a way to add a description to attributes (e.g. SQL DDL, Protobuf)
- Technical schemas (e.g. Protobuf, JSON Schema, Avro) are not very intuitive for business users
- We might need a way to add mappings between attributes in different data models (what represent the same data, what are relationships, context mapping)

**Comment by jgsmith** [comment]
Are you familiar with the linked data/semantic web community? There might be a lot of resources there that could help with this aspect of the contracts.

**Comment by jochenchrist** [comment]
Semantics are now implemented with _definitions_.
