### ISSUE TITLE
Automatically update JSON Schema in the global registry

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#11]
Should automatically update https://raw.githubusercontent.com/datacontract/datacontract-specification/main/datacontract.schema.json whenever we update `datacontract.schema.json`

**Comment by stefannegele** [comment]
Can you clarify this? Doesn't the file update automatically? Or do you mean the schema registry?

**Comment by jochenchrist** [comment]
The json schema in schema.org is linked.
