### ISSUE TITLE
Add more options to [servers, type]

### ISSUE THREAD

**Issue by larshei** [datacontract/datacontract-specification#18]
Hey there,

currently, snowflake/bigquery/dbt and maybe a few more are supported.

I would like the following types (and parameters) to be added:

- relational db (server, db, table, user)
- azure (not quite sure which parameters)
- api (url, authorization method <- follow openAPI here?) 
- rabbitmq (vhost, exchange, routing keys)

would that be of interest?

I can try to provide suggestions as a PR if desired :)

**Comment by simonharrer** [comment]
Hi @larshei, thanks for your proposal. Yes, this would be of interest.

As `api` (asyncapi or openapi?), `rabbitmq`, and `azure` (is quite big, which azure service?) would require a bit more thought, I propose to start with relational databases, perhaps even with the largest provider, that is `postgres`. Would you be so kind to draft a PR for support of `postgres `? Or did you have another relational database in mind?

**Comment by jochenchrist** [comment]
Thank you for your suggestion, I think, more server types make sense. 

We recently added `postgres` and `pubsub` server types.

For others, I'd suggest opening separate tickets per server type.
So I will close this ticket for now.
