### ISSUE TITLE
Add attribute model.classification 

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#20]
# Status Quo

Fields themselves can be classified like restricted, sensitive, etc. 

# Motivation

Combining two or more fields might result in a higher classification than the classification of the individual fields. We currently cannot encode this situation.

# Proposal

Add `classification` to the model.

**Comment by jochenchrist** [comment]
Could also be on datacontract.info level

**Comment by jochenchrist** [comment]
stale
