### ISSUE TITLE
Automatically validate all examples against the specification via GitHub Actions

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#22]
To make sure, that the examples ([datacontract.init.yaml](https://github.com/datacontract/datacontract-specification/blob/main/datacontract.init.yaml), and the example in the README (that we need to extract from there for the validation)) are valid according to the specification, we should validate them on every change via GitHub actions. We could employ a simple validation, or use the datacontract cli tool.

**Comment by jochenchrist** [comment]
Implemented in https://github.com/datacontract/datacontract-specification/blob/main/.github/workflows/ci.yaml
