### ISSUE TITLE
Add info.status

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#28]
Add the status field to the info block:

```
dataContractSpecification: 0.9.2
id: my-id
info:
  title: My Data Contract
  version: 0.0.1
  status: in development
```

Possible status values: proposed, in development, active, retired

**Comment by saugerDecathlon** [comment]
It would be useful for my use cases 👍

**Comment by simonharrer** [comment]
I've added info.status with the possible values "proposed", "in development", "active", and "retired".
