### ISSUE TITLE
Add links in info block

### ISSUE THREAD

**Issue by simonharrer** [datacontract/datacontract-specification#30]
Links are useful to specify.

```
dataContractSpecification: 0.9.2
id: covid_cases
info:
  title: COVID-19 cases
  description: Johns Hopkins University Consolidated data on COVID-19 cases, sourced from Enigma
  version: "0.0.1"
  links:
    blog: https://aws.amazon.com/blogs/big-data/a-public-data-lake-for-analysis-of-covid-19-data/
    data-explorer: https://dj2taa9i652rf.cloudfront.net/
    data: https://covid19-lake.s3.us-east-2.amazonaws.com/enigma-jhu/json/part-00000-adec1cd2-96df-4c6b-a5f2-780f092951ba-c000.json
```

We should support such links in the spec, so everybody knows a place where to put them. And putting them prominently in the info block seems like a great idea.

**Comment by jochenchrist** [comment]
TBD: 
OpenAPI uses [externalDocs](https://spec.openapis.org/oas/latest.html#external-documentation-object) for links on top level, but it is more specific than just "links".

**Comment by jochenchrist** [comment]
Links are also relevant for definitions

**Comment by simonharrer** [comment]
Decision:

links and tags on top level.
