### ISSUE TITLE
Supplement S3 Server documentation to explicitly mention interoperability with GCS

### ISSUE THREAD

**Issue by hcrosse** [datacontract/datacontract-specification#71]
Ref [datacontract-cli issue 231](https://github.com/datacontract/datacontract-cli/issues/231)

Update S3 server object documentation to explicitly mention compatibility with GCS using a `gs://` location and endpointUrl.

**Comment by hcrosse** [comment]
I haven't actually tested that the above functionality is possible - will do so if/when I get the opportunity (and then I can create a PR to implement this if someone else hasn't beaten me to it).

**Comment by jochenchrist** [comment]
OK, let's add explicit support for server type gcs.

**Comment by jochenchrist** [comment]
Discarded, we continue to use S3.
